question_data = [
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "All of the following programs are classified as raster graphics editors EXCEPT:",
     "correct_answer": "Inkscape", "incorrect_answers": ["Paint.NET", "GIMP", "Adobe Photoshop"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "How many kilobytes in one gigabyte (in decimal)?", "correct_answer": "1000000",
     "incorrect_answers": ["1024", "1000", "1048576"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "AMD created the first consumer 64-bit processor.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
                                       "question": "Who is the original author of the realtime physics engine called PhysX?",
                                       "correct_answer": "NovodeX",
                                       "incorrect_answers": ["Ageia", "Nvidia", "AMD"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": ".at is the top-level domain for what country?", "correct_answer": "Austria",
     "incorrect_answers": ["Argentina", "Australia", "Angola"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Laserjet and inkjet printers are both examples of what type of printer?",
     "correct_answer": "Non-impact printer",
     "incorrect_answers": ["Impact printer", "Daisywheel printer", "Dot matrix printer"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "Which of the following computer components can be built using only NAND gates?",
     "correct_answer": "ALU", "incorrect_answers": ["CPU", "RAM", "Register"]}]
